# Model Context Protocol Server Image

FROM python:3.12-slim

WORKDIR /mcp_india_kanoon

COPY ./backend/Pipfile /mcp_india_kanoon/Pipfile

RUN python -m pip install --upgrade pip

COPY ./backend/mcp_india_kanoon /mcp_india_kanoon

RUN pip install pipenv 

RUN pipenv lock && pipenv install --system --deploy --ignore-pipfile

CMD [ "python" , "main.py"]