services:
  backend:
    hostname: ai_backend
    build: 
      context: .
      dockerfile: Dockerfile_api
    networks:
      - paralegal-ai-bot-network 
    ports:
      - "8001:8001"
  
  mcp_india_kanoon:
    hostname: mcp_india_kanoon
    build: 
      context: .
      dockerfile: Dockerfile_mcp
    networks:
      - paralegal-ai-bot-network
    ports:
      - "8000"

networks:
  paralegal-ai-bot-network:
    driver: bridge


    