# Model Context Protocol Server Image

FROM python:3.12-slim

WORKDIR /mcp_india_kanoon

COPY ./backend/Pipfile /mcp_india_kanoon/Pipfile

COPY ./.env /mcp_india_kanoon/.env

RUN python -m pip install --upgrade pip

COPY ./backend/mcp_india_kanoon /mcp_india_kanoon

RUN pip install pipenv 

RUN pipenv lock && pipenv install --system --deploy --ignore-pipfile

RUN crawl4ai-setup

RUN crawl4ai-doctor

CMD [ "python" , "main.py"]