# Backend api server image

FROM python:3.12-slim

WORKDIR /app

COPY ./backend/Pipfile /Pipfile

RUN python -m pip install --upgrade pip

COPY ./backend/app /app

RUN pip install pipenv 

RUN pipenv lock && pipenv install --system --deploy --ignore-pipfile

CMD ["python", "main.py"]